// Generated by tools/gen_gles.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace zb {

inline constexpr std::uint32_t kGlHostCallFirst = 0;
inline constexpr std::uint32_t kGlHostCallLast = 141;
inline constexpr std::size_t kGlHostCallCount = 142;
inline constexpr std::size_t kGlPointerlessHostCallCount = 81;

inline constexpr std::uint32_t ZB_GL_HC_glActiveTexture = 0u;
inline constexpr std::uint32_t ZB_GL_HC_glAttachShader = 1u;
inline constexpr std::uint32_t ZB_GL_HC_glBindAttribLocation = 2u;
inline constexpr std::uint32_t ZB_GL_HC_glBindBuffer = 3u;
inline constexpr std::uint32_t ZB_GL_HC_glBindFramebuffer = 4u;
inline constexpr std::uint32_t ZB_GL_HC_glBindRenderbuffer = 5u;
inline constexpr std::uint32_t ZB_GL_HC_glBindTexture = 6u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendColor = 7u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendEquation = 8u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendEquationSeparate = 9u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendFunc = 10u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendFuncSeparate = 11u;
inline constexpr std::uint32_t ZB_GL_HC_glBufferData = 12u;
inline constexpr std::uint32_t ZB_GL_HC_glBufferSubData = 13u;
inline constexpr std::uint32_t ZB_GL_HC_glCheckFramebufferStatus = 14u;
inline constexpr std::uint32_t ZB_GL_HC_glClear = 15u;
inline constexpr std::uint32_t ZB_GL_HC_glClearColor = 16u;
inline constexpr std::uint32_t ZB_GL_HC_glClearDepthf = 17u;
inline constexpr std::uint32_t ZB_GL_HC_glClearStencil = 18u;
inline constexpr std::uint32_t ZB_GL_HC_glColorMask = 19u;
inline constexpr std::uint32_t ZB_GL_HC_glCompileShader = 20u;
inline constexpr std::uint32_t ZB_GL_HC_glCompressedTexImage2D = 21u;
inline constexpr std::uint32_t ZB_GL_HC_glCompressedTexSubImage2D = 22u;
inline constexpr std::uint32_t ZB_GL_HC_glCopyTexImage2D = 23u;
inline constexpr std::uint32_t ZB_GL_HC_glCopyTexSubImage2D = 24u;
inline constexpr std::uint32_t ZB_GL_HC_glCreateProgram = 25u;
inline constexpr std::uint32_t ZB_GL_HC_glCreateShader = 26u;
inline constexpr std::uint32_t ZB_GL_HC_glCullFace = 27u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteBuffers = 28u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteFramebuffers = 29u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteProgram = 30u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteRenderbuffers = 31u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteShader = 32u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteTextures = 33u;
inline constexpr std::uint32_t ZB_GL_HC_glDepthFunc = 34u;
inline constexpr std::uint32_t ZB_GL_HC_glDepthMask = 35u;
inline constexpr std::uint32_t ZB_GL_HC_glDepthRangef = 36u;
inline constexpr std::uint32_t ZB_GL_HC_glDetachShader = 37u;
inline constexpr std::uint32_t ZB_GL_HC_glDisable = 38u;
inline constexpr std::uint32_t ZB_GL_HC_glDisableVertexAttribArray = 39u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawArrays = 40u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawElements = 41u;
inline constexpr std::uint32_t ZB_GL_HC_glEnable = 42u;
inline constexpr std::uint32_t ZB_GL_HC_glEnableVertexAttribArray = 43u;
inline constexpr std::uint32_t ZB_GL_HC_glFinish = 44u;
inline constexpr std::uint32_t ZB_GL_HC_glFlush = 45u;
inline constexpr std::uint32_t ZB_GL_HC_glFramebufferRenderbuffer = 46u;
inline constexpr std::uint32_t ZB_GL_HC_glFramebufferTexture2D = 47u;
inline constexpr std::uint32_t ZB_GL_HC_glFrontFace = 48u;
inline constexpr std::uint32_t ZB_GL_HC_glGenBuffers = 49u;
inline constexpr std::uint32_t ZB_GL_HC_glGenFramebuffers = 50u;
inline constexpr std::uint32_t ZB_GL_HC_glGenRenderbuffers = 51u;
inline constexpr std::uint32_t ZB_GL_HC_glGenTextures = 52u;
inline constexpr std::uint32_t ZB_GL_HC_glGenerateMipmap = 53u;
inline constexpr std::uint32_t ZB_GL_HC_glGetActiveAttrib = 54u;
inline constexpr std::uint32_t ZB_GL_HC_glGetActiveUniform = 55u;
inline constexpr std::uint32_t ZB_GL_HC_glGetAttachedShaders = 56u;
inline constexpr std::uint32_t ZB_GL_HC_glGetAttribLocation = 57u;
inline constexpr std::uint32_t ZB_GL_HC_glGetBooleanv = 58u;
inline constexpr std::uint32_t ZB_GL_HC_glGetBufferParameteriv = 59u;
inline constexpr std::uint32_t ZB_GL_HC_glGetError = 60u;
inline constexpr std::uint32_t ZB_GL_HC_glGetFloatv = 61u;
inline constexpr std::uint32_t ZB_GL_HC_glGetFramebufferAttachmentParameteriv = 62u;
inline constexpr std::uint32_t ZB_GL_HC_glGetIntegerv = 63u;
inline constexpr std::uint32_t ZB_GL_HC_glGetProgramInfoLog = 64u;
inline constexpr std::uint32_t ZB_GL_HC_glGetProgramiv = 65u;
inline constexpr std::uint32_t ZB_GL_HC_glGetRenderbufferParameteriv = 66u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderInfoLog = 67u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderPrecisionFormat = 68u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderSource = 69u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderiv = 70u;
inline constexpr std::uint32_t ZB_GL_HC_glGetString = 71u;
inline constexpr std::uint32_t ZB_GL_HC_glGetTexParameterfv = 72u;
inline constexpr std::uint32_t ZB_GL_HC_glGetTexParameteriv = 73u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformLocation = 74u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformfv = 75u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformiv = 76u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribPointerv = 77u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribfv = 78u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribiv = 79u;
inline constexpr std::uint32_t ZB_GL_HC_glHint = 80u;
inline constexpr std::uint32_t ZB_GL_HC_glIsBuffer = 81u;
inline constexpr std::uint32_t ZB_GL_HC_glIsEnabled = 82u;
inline constexpr std::uint32_t ZB_GL_HC_glIsFramebuffer = 83u;
inline constexpr std::uint32_t ZB_GL_HC_glIsProgram = 84u;
inline constexpr std::uint32_t ZB_GL_HC_glIsRenderbuffer = 85u;
inline constexpr std::uint32_t ZB_GL_HC_glIsShader = 86u;
inline constexpr std::uint32_t ZB_GL_HC_glIsTexture = 87u;
inline constexpr std::uint32_t ZB_GL_HC_glLineWidth = 88u;
inline constexpr std::uint32_t ZB_GL_HC_glLinkProgram = 89u;
inline constexpr std::uint32_t ZB_GL_HC_glPixelStorei = 90u;
inline constexpr std::uint32_t ZB_GL_HC_glPolygonOffset = 91u;
inline constexpr std::uint32_t ZB_GL_HC_glReadPixels = 92u;
inline constexpr std::uint32_t ZB_GL_HC_glReleaseShaderCompiler = 93u;
inline constexpr std::uint32_t ZB_GL_HC_glRenderbufferStorage = 94u;
inline constexpr std::uint32_t ZB_GL_HC_glSampleCoverage = 95u;
inline constexpr std::uint32_t ZB_GL_HC_glScissor = 96u;
inline constexpr std::uint32_t ZB_GL_HC_glShaderBinary = 97u;
inline constexpr std::uint32_t ZB_GL_HC_glShaderSource = 98u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilFunc = 99u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilFuncSeparate = 100u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilMask = 101u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilMaskSeparate = 102u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilOp = 103u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilOpSeparate = 104u;
inline constexpr std::uint32_t ZB_GL_HC_glTexImage2D = 105u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameterf = 106u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameterfv = 107u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameteri = 108u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameteriv = 109u;
inline constexpr std::uint32_t ZB_GL_HC_glTexSubImage2D = 110u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1f = 111u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1fv = 112u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1i = 113u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1iv = 114u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2f = 115u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2fv = 116u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2i = 117u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2iv = 118u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3f = 119u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3fv = 120u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3i = 121u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3iv = 122u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4f = 123u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4fv = 124u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4i = 125u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4iv = 126u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix2fv = 127u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix3fv = 128u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix4fv = 129u;
inline constexpr std::uint32_t ZB_GL_HC_glUseProgram = 130u;
inline constexpr std::uint32_t ZB_GL_HC_glValidateProgram = 131u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib1f = 132u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib1fv = 133u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib2f = 134u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib2fv = 135u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib3f = 136u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib3fv = 137u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib4f = 138u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib4fv = 139u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribPointer = 140u;
inline constexpr std::uint32_t ZB_GL_HC_glViewport = 141u;

struct GlHostCallInfo {
    std::uint32_t index;
    const char* name;
    bool has_pointer;
};

inline constexpr std::array<GlHostCallInfo, kGlHostCallCount> kGlHostCalls{{
    {0u, "glActiveTexture", false},
    {1u, "glAttachShader", false},
    {2u, "glBindAttribLocation", true},
    {3u, "glBindBuffer", false},
    {4u, "glBindFramebuffer", false},
    {5u, "glBindRenderbuffer", false},
    {6u, "glBindTexture", false},
    {7u, "glBlendColor", false},
    {8u, "glBlendEquation", false},
    {9u, "glBlendEquationSeparate", false},
    {10u, "glBlendFunc", false},
    {11u, "glBlendFuncSeparate", false},
    {12u, "glBufferData", true},
    {13u, "glBufferSubData", true},
    {14u, "glCheckFramebufferStatus", false},
    {15u, "glClear", false},
    {16u, "glClearColor", false},
    {17u, "glClearDepthf", false},
    {18u, "glClearStencil", false},
    {19u, "glColorMask", false},
    {20u, "glCompileShader", false},
    {21u, "glCompressedTexImage2D", true},
    {22u, "glCompressedTexSubImage2D", true},
    {23u, "glCopyTexImage2D", false},
    {24u, "glCopyTexSubImage2D", false},
    {25u, "glCreateProgram", false},
    {26u, "glCreateShader", false},
    {27u, "glCullFace", false},
    {28u, "glDeleteBuffers", true},
    {29u, "glDeleteFramebuffers", true},
    {30u, "glDeleteProgram", false},
    {31u, "glDeleteRenderbuffers", true},
    {32u, "glDeleteShader", false},
    {33u, "glDeleteTextures", true},
    {34u, "glDepthFunc", false},
    {35u, "glDepthMask", false},
    {36u, "glDepthRangef", false},
    {37u, "glDetachShader", false},
    {38u, "glDisable", false},
    {39u, "glDisableVertexAttribArray", false},
    {40u, "glDrawArrays", false},
    {41u, "glDrawElements", true},
    {42u, "glEnable", false},
    {43u, "glEnableVertexAttribArray", false},
    {44u, "glFinish", false},
    {45u, "glFlush", false},
    {46u, "glFramebufferRenderbuffer", false},
    {47u, "glFramebufferTexture2D", false},
    {48u, "glFrontFace", false},
    {49u, "glGenBuffers", true},
    {50u, "glGenFramebuffers", true},
    {51u, "glGenRenderbuffers", true},
    {52u, "glGenTextures", true},
    {53u, "glGenerateMipmap", false},
    {54u, "glGetActiveAttrib", true},
    {55u, "glGetActiveUniform", true},
    {56u, "glGetAttachedShaders", true},
    {57u, "glGetAttribLocation", true},
    {58u, "glGetBooleanv", true},
    {59u, "glGetBufferParameteriv", true},
    {60u, "glGetError", false},
    {61u, "glGetFloatv", true},
    {62u, "glGetFramebufferAttachmentParameteriv", true},
    {63u, "glGetIntegerv", true},
    {64u, "glGetProgramInfoLog", true},
    {65u, "glGetProgramiv", true},
    {66u, "glGetRenderbufferParameteriv", true},
    {67u, "glGetShaderInfoLog", true},
    {68u, "glGetShaderPrecisionFormat", true},
    {69u, "glGetShaderSource", true},
    {70u, "glGetShaderiv", true},
    {71u, "glGetString", false},
    {72u, "glGetTexParameterfv", true},
    {73u, "glGetTexParameteriv", true},
    {74u, "glGetUniformLocation", true},
    {75u, "glGetUniformfv", true},
    {76u, "glGetUniformiv", true},
    {77u, "glGetVertexAttribPointerv", true},
    {78u, "glGetVertexAttribfv", true},
    {79u, "glGetVertexAttribiv", true},
    {80u, "glHint", false},
    {81u, "glIsBuffer", false},
    {82u, "glIsEnabled", false},
    {83u, "glIsFramebuffer", false},
    {84u, "glIsProgram", false},
    {85u, "glIsRenderbuffer", false},
    {86u, "glIsShader", false},
    {87u, "glIsTexture", false},
    {88u, "glLineWidth", false},
    {89u, "glLinkProgram", false},
    {90u, "glPixelStorei", false},
    {91u, "glPolygonOffset", false},
    {92u, "glReadPixels", true},
    {93u, "glReleaseShaderCompiler", false},
    {94u, "glRenderbufferStorage", false},
    {95u, "glSampleCoverage", false},
    {96u, "glScissor", false},
    {97u, "glShaderBinary", true},
    {98u, "glShaderSource", true},
    {99u, "glStencilFunc", false},
    {100u, "glStencilFuncSeparate", false},
    {101u, "glStencilMask", false},
    {102u, "glStencilMaskSeparate", false},
    {103u, "glStencilOp", false},
    {104u, "glStencilOpSeparate", false},
    {105u, "glTexImage2D", true},
    {106u, "glTexParameterf", false},
    {107u, "glTexParameterfv", true},
    {108u, "glTexParameteri", false},
    {109u, "glTexParameteriv", true},
    {110u, "glTexSubImage2D", true},
    {111u, "glUniform1f", false},
    {112u, "glUniform1fv", true},
    {113u, "glUniform1i", false},
    {114u, "glUniform1iv", true},
    {115u, "glUniform2f", false},
    {116u, "glUniform2fv", true},
    {117u, "glUniform2i", false},
    {118u, "glUniform2iv", true},
    {119u, "glUniform3f", false},
    {120u, "glUniform3fv", true},
    {121u, "glUniform3i", false},
    {122u, "glUniform3iv", true},
    {123u, "glUniform4f", false},
    {124u, "glUniform4fv", true},
    {125u, "glUniform4i", false},
    {126u, "glUniform4iv", true},
    {127u, "glUniformMatrix2fv", true},
    {128u, "glUniformMatrix3fv", true},
    {129u, "glUniformMatrix4fv", true},
    {130u, "glUseProgram", false},
    {131u, "glValidateProgram", false},
    {132u, "glVertexAttrib1f", false},
    {133u, "glVertexAttrib1fv", true},
    {134u, "glVertexAttrib2f", false},
    {135u, "glVertexAttrib2fv", true},
    {136u, "glVertexAttrib3f", false},
    {137u, "glVertexAttrib3fv", true},
    {138u, "glVertexAttrib4f", false},
    {139u, "glVertexAttrib4fv", true},
    {140u, "glVertexAttribPointer", true},
    {141u, "glViewport", false},
}};

}  // namespace zb
