#!/usr/bin/env python3
"""Generate arm32 guest stub libraries whose functions trap into the host.

Every exported function is two ARM-mode instructions:
    svc #(0x5A0000 | index)
    bx  lr
The svc immediate identifies the host call; arguments stay in r0-r3 and on the guest
stack exactly as the caller placed them (AAPCS softfp), so the host handler can read
them. Indices 0xFE00-0xFEFF are reserved for the library runtime
(core/include/zb/library_protocol.h) and 0xFFFF for returning from host->guest calls, so
generated indices must stay below 0xFE00.

Outputs (committed):
  guest/stubs/gen/<lib>.S        one assembly file per stub library
  core/src/gen/hostcalls.inc     {index, "lib", "name"} rows for the host dispatcher
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NDK = os.environ.get("NDK", os.path.expanduser("~/android-ndk-r29"))
NDK_HOST = os.environ.get("NDK_HOST", "linux-arm64")
INCLUDE = os.path.join(NDK, "toolchains", "llvm", "prebuilt", NDK_HOST, "sysroot", "usr", "include")

HOST_CALL_BASE = 0x5A0000
HOST_RETURN_INDEX = 0xFFFF
# ZB_RUNTIME_HOST_CALL_FIRST..LAST in core/include/zb/library_protocol.h.
RUNTIME_HOST_CALL_FIRST = 0xFE00


def gles2_names():
    text = open(os.path.join(INCLUDE, "GLES2", "gl2.h")).read()
    return sorted(set(re.findall(r"GL_APICALL\s+[^;]*?GL_APIENTRY\s+(gl\w+)\s*\(", text)))


def android_asset_names():
    names = set()
    decl = re.compile(r"^[A-Za-z_][\w \*]*\b(AAsset\w*)\(")
    for header in ("asset_manager.h", "asset_manager_jni.h"):
        for line in open(os.path.join(INCLUDE, "android", header)):
            m = decl.match(line)
            if m:
                names.add(m.group(1))
    return sorted(names)


LIBRARIES = [
    ("libGLESv2", gles2_names),
    ("libandroid", android_asset_names),
]


def main():
    out_asm = os.path.join(ROOT, "guest", "stubs", "gen")
    out_host = os.path.join(ROOT, "core", "src", "gen")
    os.makedirs(out_asm, exist_ok=True)
    os.makedirs(out_host, exist_ok=True)

    index = 0
    rows = []
    for lib, source in LIBRARIES:
        names = source()
        if not names:
            sys.exit("no functions found for " + lib)
        lines = [
            "@ Generated by tools/gen_stubs.py. Do not edit.",
            ".syntax unified",
            ".arm",
            ".text",
            "",
        ]
        for name in names:
            if index >= RUNTIME_HOST_CALL_FIRST:
                sys.exit("too many host calls: index 0x%x reaches the runtime range" % index)
            lines += [
                ".global %s" % name,
                ".type %s, %%function" % name,
                ".p2align 2",
                "%s:" % name,
                "    svc #0x%x" % (HOST_CALL_BASE | index),
                "    bx lr",
                ".size %s, . - %s" % (name, name),
                "",
            ]
            rows.append((index, lib + ".so", name))
            index += 1
        with open(os.path.join(out_asm, lib + ".S"), "w") as f:
            f.write("\n".join(lines))
        print("%s: %d functions" % (lib, len(names)))

    with open(os.path.join(out_host, "hostcalls.inc"), "w") as f:
        f.write("// Generated by tools/gen_stubs.py. Do not edit.\n")
        for i, lib, name in rows:
            f.write('{%d, "%s", "%s"},\n' % (i, lib, name))
    print("host calls: %d" % index)


if __name__ == "__main__":
    main()
