#!/usr/bin/env python3
"""Generate the GLES 2.0 host-call protocol and Task 1 dispatcher.

The Khronos registry copy was downloaded on 2026-09-16 from:
https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/main/xml/gl.xml

Inputs:
  third_party/registry/gl.xml                  pinned Khronos registry
  NDK sysroot/usr/include/GLES2/gl2.h          exported GLES 2.0 names
  core/src/gen/hostcalls.inc                   guest stub index assignment

Outputs are committed. Run with --check to reject stale files.
"""

import os
import re
import sys
import xml.etree.ElementTree as ET

sys.dont_write_bytecode = True
import gen_stubs


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, "third_party", "registry", "gl.xml")
HOSTCALLS = os.path.join(ROOT, "core", "src", "gen", "hostcalls.inc")
EXPECTED_GLES = 142
EXPECTED_POINTERLESS = 81
EXPECTED_TASK3_MECHANICAL = 125
HEADER = "Generated by tools/gen_gles.py. Do not edit."

# Semantic handlers from the approved design. glGetString is the important Task 1 exception:
# it has no pointer parameter, but its host-pointer return must never be copied into guest r0.
HANDWRITTEN = {
    "glDrawArrays",
    "glDrawElements",
    "glGetString",
    "glGetUniformfv",
    "glGetUniformiv",
    "glGetVertexAttribPointerv",
    "glReadPixels",
    "glShaderSource",
    "glTexImage2D",
    "glTexSubImage2D",
    "glVertexAttribPointer",
}

TASK3_ONE_ELEMENT_COMPSIZE = {
    "glGetBufferParameteriv",
    "glGetFramebufferAttachmentParameteriv",
    "glGetProgramiv",
    "glGetRenderbufferParameteriv",
    "glGetShaderiv",
    "glGetTexParameterfv",
    "glGetTexParameteriv",
    "glTexParameterfv",
    "glTexParameteriv",
}


class Parameter:
    def __init__(self, declaration, name, length):
        self.declaration = declaration
        self.name = name
        self.length = length

    @property
    def pointer(self):
        return "*" in self.declaration


class Command:
    def __init__(self, name, result, parameters):
        self.name = name
        self.result = result
        self.parameters = parameters

    @property
    def pointer(self):
        return any(parameter.pointer for parameter in self.parameters)


def pointer_pointee(parameter):
    prefix = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
    if prefix.count("*") != 1:
        return None
    return prefix[:prefix.rfind("*")].strip()


def length_rule(command, parameter):
    length = parameter.length
    if length == "COMPSIZE(pname)" and command.name in TASK3_ONE_ELEMENT_COMPSIZE:
        return (None, 1)
    if length is None or length.startswith("COMPSIZE"):
        return None
    if re.fullmatch(r"[1-4]", length):
        return (None, int(length))
    match = re.fullmatch(r"([A-Za-z_]\w*)(?:\*(1|2|3|4|9|16))?", length)
    if match is None:
        return None
    return (match.group(1), int(match.group(2) or "1"))


def mechanical(command):
    if command.name in HANDWRITTEN:
        return False
    return all(pointer_pointee(parameter) is not None and length_rule(command, parameter) is not None
               for parameter in command.parameters if parameter.pointer)


def element_text(element):
    return "".join(element.itertext()).strip()


def registry_commands():
    root = ET.parse(REGISTRY).getroot()
    feature = root.find("./feature[@name='GL_ES_VERSION_2_0']")
    if feature is None:
        sys.exit("gl.xml: GL_ES_VERSION_2_0 not found")
    names = []
    for requirement in feature.findall("require"):
        names.extend(node.get("name") for node in requirement.findall("command"))
    if len(names) != EXPECTED_GLES or len(set(names)) != EXPECTED_GLES:
        sys.exit("gl.xml: expected %d unique GLES 2.0 commands, got %d (%d unique)" %
                 (EXPECTED_GLES, len(names), len(set(names))))

    definitions = {}
    for node in root.findall("./commands/command"):
        proto = node.find("proto")
        if proto is None:
            continue
        name = proto.findtext("name")
        definitions[name] = node

    commands = {}
    for name in names:
        node = definitions.get(name)
        if node is None:
            sys.exit("gl.xml: command definition missing for " + name)
        proto = element_text(node.find("proto"))
        if not proto.endswith(name):
            sys.exit("gl.xml: malformed prototype for " + name)
        result = proto[:-len(name)].strip()
        parameters = []
        for param in node.findall("param"):
            param_name = param.findtext("name")
            declaration = element_text(param)
            if not param_name or not re.search(r"\b%s\b" % re.escape(param_name), declaration):
                sys.exit("gl.xml: malformed parameter in " + name)
            parameters.append(Parameter(declaration, param_name, param.get("len")))
        commands[name] = Command(name, result, parameters)
    return commands


def committed_hostcalls():
    rows = []
    row = re.compile(r'^\{(\d+), "([^"]+)", "([^"]+)"\},$')
    with open(HOSTCALLS) as source:
        for line in source:
            match = row.match(line.strip())
            if match:
                rows.append((int(match.group(1)), match.group(2), match.group(3)))
    return rows


def checked_surface():
    commands = registry_commands()
    header_names = gen_stubs.gles2_names()
    registry_names = sorted(commands)
    if len(header_names) != EXPECTED_GLES:
        sys.exit("gl2.h: expected %d functions, got %d" % (EXPECTED_GLES, len(header_names)))
    missing_header = sorted(set(registry_names) - set(header_names))
    missing_registry = sorted(set(header_names) - set(registry_names))
    if missing_header or missing_registry:
        sys.exit("GLES surface mismatch: registry-only=%s header-only=%s" %
                 (missing_header, missing_registry))

    expected_rows = []
    index = 0
    for name in header_names:
        expected_rows.append((index, "libGLESv2.so", name))
        index += 1
    for name in gen_stubs.android_asset_names():
        expected_rows.append((index, "libandroid.so", name))
        index += 1
    actual_rows = committed_hostcalls()
    if actual_rows != expected_rows:
        sys.exit("core/src/gen/hostcalls.inc disagrees with tools/gen_stubs.py")

    ordered = [commands[name] for name in header_names]
    pointerless = sum(not command.pointer for command in ordered)
    if pointerless != EXPECTED_POINTERLESS:
        sys.exit("gl.xml: expected %d pointerless commands, got %d" %
                 (EXPECTED_POINTERLESS, pointerless))
    task3_mechanical = sum(mechanical(command) for command in ordered)
    if task3_mechanical != EXPECTED_TASK3_MECHANICAL:
        sys.exit("gl.xml: expected %d Task 3 mechanical commands, got %d" %
                 (EXPECTED_TASK3_MECHANICAL, task3_mechanical))
    return ordered


def backend_header(commands):
    lines = [
        "// " + HEADER,
        "#pragma once",
        "",
        "#include <bit>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <initializer_list>",
        "#include <type_traits>",
        "",
        "namespace zb {",
        "",
        "using GLbitfield = std::uint32_t;",
        "using GLboolean = std::uint8_t;",
        "using GLchar = char;",
        "using GLenum = std::uint32_t;",
        "using GLfloat = float;",
        "using GLint = std::int32_t;",
        "using GLintptr = std::intptr_t;",
        "using GLsizei = std::int32_t;",
        "using GLsizeiptr = std::ptrdiff_t;",
        "using GLubyte = std::uint8_t;",
        "using GLuint = std::uint32_t;",
        "",
        "inline constexpr GLenum kGlInvalidValue = 0x0501;",
        "inline constexpr GLenum kGlInvalidOperation = 0x0502;",
        "",
        "template <typename T>",
        "inline std::uint64_t gl_backend_word(T value) {",
        "    if constexpr (std::is_pointer_v<T>) {",
        "        return static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(value));",
        "    } else if constexpr (std::is_floating_point_v<T>) {",
        "        return std::bit_cast<std::uint32_t>(value);",
        "    } else {",
        "        return static_cast<std::uint64_t>(value);",
        "    }",
        "}",
        "",
        "// The portable GLES seam. Android overrides the typed entry points; host tests use",
        "// invoke() to record the same typed calls without linking a GLES implementation.",
        "class GlBackend {",
        "public:",
        "    virtual ~GlBackend() = default;",
        "    virtual void set_error(GLenum error) = 0;",
        "",
    ]
    for command in commands:
        params = ", ".join(parameter.declaration for parameter in command.parameters) or "void"
        args = ", ".join("gl_backend_word(%s)" % parameter.name for parameter in command.parameters)
        invocation = 'invoke("%s", {%s})' % (command.name, args)
        lines.append("    virtual %s %s(%s) {" % (command.result, command.name, params))
        if command.result == "void":
            lines.append("        (void)%s;" % invocation)
        elif "*" in command.result:
            lines.append("        return reinterpret_cast<%s>(static_cast<std::uintptr_t>(%s));" %
                         (command.result, invocation))
        else:
            lines.append("        return static_cast<%s>(%s);" % (command.result, invocation))
        lines.append("    }")
    lines += [
        "",
        "protected:",
        "    virtual std::uint64_t invoke(const char* name,",
        "                                 std::initializer_list<std::uint64_t> arguments) = 0;",
        "};",
        "",
        "}  // namespace zb",
    ]
    return "\n".join(lines) + "\n"


def hostcalls_header(commands):
    lines = [
        "// " + HEADER,
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace zb {",
        "",
        "inline constexpr std::uint32_t kGlHostCallFirst = 0;",
        "inline constexpr std::uint32_t kGlHostCallLast = 141;",
        "inline constexpr std::size_t kGlHostCallCount = 142;",
        "inline constexpr std::size_t kGlPointerlessHostCallCount = 81;",
        "",
    ]
    for index, command in enumerate(commands):
        lines.append("inline constexpr std::uint32_t ZB_GL_HC_%s = %du;" %
                     (command.name, index))
    lines += [
        "",
        "struct GlHostCallInfo {",
        "    std::uint32_t index;",
        "    const char* name;",
        "    bool has_pointer;",
        "};",
        "",
        "inline constexpr std::array<GlHostCallInfo, kGlHostCallCount> kGlHostCalls{{",
    ]
    for index, command in enumerate(commands):
        lines.append('    {%du, "%s", %s},' %
                     (index, command.name, "true" if command.pointer else "false"))
    lines += ["}};", "", "}  // namespace zb"]
    return "\n".join(lines) + "\n"


def manual_include(commands):
    lines = [
        "// " + HEADER,
    ]
    for command in commands:
        if not mechanical(command):
            lines.append("bool zbgl_manual_%s(HostGl& host, HostGl::Call& call);" % command.name)
    return "\n".join(lines) + "\n"


def dispatch_include(commands):
    lines = [
        "// " + HEADER,
        "bool HostGl::dispatch(Call& call) {",
        "    switch (call.index()) {",
    ]
    for command in commands:
        lines.append("    case ZB_GL_HC_%s: {" % command.name)
        if not mechanical(command):
            lines.append("        return zbgl_manual_%s(*this, call);" % command.name)
        else:
            for position, parameter in enumerate(command.parameters):
                if parameter.pointer:
                    continue
                ptype = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
                lines.append("        const %s %s = call.scalar<%s>(%d);" %
                             (ptype, parameter.name, ptype, position))
            for position, parameter in enumerate(command.parameters):
                if not parameter.pointer:
                    continue
                declaration = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
                pointee = pointer_pointee(parameter)
                length_name, multiplier = length_rule(command, parameter)
                if length_name is None:
                    elements = "%du" % multiplier
                else:
                    elements = "call.length(%s, %du)" % (length_name, multiplier)
                permission = "kPageRead" if "const" in pointee.split() else "kPageRead | kPageWrite"
                lines.append("        %s %s = call.pointer<%s>(%d, %s, %s);" %
                             (declaration, parameter.name, pointee, position, elements, permission))
            lines.append("        if (!call.valid()) return true;")
            args = ", ".join(parameter.name for parameter in command.parameters)
            invocation = "backend_.%s(%s)" % (command.name, args)
            if command.result == "void":
                lines.append("        %s;" % invocation)
                if command.name == "glPixelStorei":
                    lines.append("        note_pixel_store(pname, param);")
                elif command.name in ("glLinkProgram", "glDeleteProgram"):
                    lines.append("        invalidate_uniforms(program);")
            else:
                lines.append("        call.set_result(%s);" % invocation)
            lines.append("        return true;")
        lines.append("    }")
    lines += [
        "    default:",
        "        return false;",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def generate():
    commands = checked_surface()
    return {
        "core/include/zb/gl_backend.h": backend_header(commands),
        "core/include/zb/gl_hostcalls.h": hostcalls_header(commands),
        "core/src/gen/gl_dispatch.inc": dispatch_include(commands),
        "core/src/gen/gl_manual.inc": manual_include(commands),
    }


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        sys.exit("usage: gen_gles.py [--check]")
    stale = []
    for path, content in generate().items():
        full = os.path.join(ROOT, path)
        if check:
            try:
                with open(full) as source:
                    current = source.read()
            except OSError:
                current = None
            if current != content:
                stale.append(path)
        else:
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w") as output:
                output.write(content)
            print("wrote " + path)
    if stale:
        print("stale generated files (run tools/gen_gles.py): " + ", ".join(stale))
        sys.exit(1)
    if check:
        print("generated GLES files are up to date")


if __name__ == "__main__":
    main()
