#!/usr/bin/env python3
"""Generate arm32 guest stub libraries whose functions trap into the host.

Every exported function is two ARM-mode instructions:
    svc #(0x5A0000 | index)
    bx  lr
The svc immediate identifies the host call; arguments stay in r0-r3 and on the guest
stack exactly as the caller placed them (AAPCS softfp), so the host handler can read
them. Indices 0xFB00-0xFCFF are reserved for the JNI bridge
(core/include/zb/jni_protocol.h), 0xFE00-0xFEFF for the library runtime
(core/include/zb/library_protocol.h) and 0xFFFF for returning from host->guest calls, so
generated indices must stay below 0xFB00.

Outputs (committed):
  guest/stubs/gen/<lib>.S        one assembly file per stub library
  core/src/gen/hostcalls.inc     {index, "lib", "name"} rows for the host dispatcher
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NDK = os.environ.get("NDK", os.path.expanduser("~/android-ndk-r29"))
NDK_HOST = os.environ.get("NDK_HOST", "linux-arm64")
INCLUDE = os.path.join(NDK, "toolchains", "llvm", "prebuilt", NDK_HOST, "sysroot", "usr", "include")

HOST_CALL_BASE = 0x5A0000
HOST_RETURN_INDEX = 0xFFFF
# ZB_JNI_SLOT_STUB_FIRST in core/include/zb/jni_protocol.h: the first index above the stubs.
RESERVED_HOST_CALL_FIRST = 0xFB00


def gles2_names():
    text = open(os.path.join(INCLUDE, "GLES2", "gl2.h")).read()
    return sorted(set(re.findall(r"GL_APICALL\s+[^;]*?GL_APIENTRY\s+(gl\w+)\s*\(", text)))


def android_asset_names():
    names = set()
    decl = re.compile(r"^[A-Za-z_][\w \*]*\b(AAsset\w*)\(")
    for header in ("asset_manager.h", "asset_manager_jni.h"):
        for line in open(os.path.join(INCLUDE, "android", header)):
            m = decl.match(line)
            if m:
                names.add(m.group(1))
    return sorted(names)


# Appended after the AAsset* names so the hand-written indices in
# core/include/zb/asset_hostcalls.h (145-157) keep pointing at the same functions.
ANATIVE_WINDOW = [
    "ANativeWindow_acquire",
    "ANativeWindow_fromSurface",
    "ANativeWindow_getFormat",
    "ANativeWindow_getHeight",
    "ANativeWindow_getWidth",
    "ANativeWindow_release",
    "ANativeWindow_setBuffersGeometry",
    "ANativeWindow_toSurface",
]


def android_names():
    return android_asset_names() + ANATIVE_WINDOW


def egl_names():
    text = open(os.path.join(INCLUDE, "EGL", "egl.h")).read()
    return sorted(set(re.findall(r"EGLAPI\s+[^;]*?EGLAPIENTRY\s+(egl\w+)\s*\(", text)))


def android_compat_names():
    return [
        "ANativeWindow_lock",
        "ANativeWindow_unlockAndPost",
    ]


def egl_compat_names():
    return [
        "eglCreateImageKHR",
        "eglDestroyImageKHR",
    ]


def gles2_compat_names():
    return ["glEGLImageTargetTexture2DOES"]


def jnigraphics_names():
    return [
        "AndroidBitmap_getInfo",
        "AndroidBitmap_lockPixels",
        "AndroidBitmap_unlockPixels",
    ]


def looper_compat_names():
    return [
        "ALooper_acquire",
        "ALooper_addFd",
        "ALooper_forThread",
        "ALooper_pollOnce",
        "ALooper_prepare",
        "ALooper_release",
        "ALooper_removeFd",
        "ALooper_wake",
    ]


LIBRARIES = [
    ("libGLESv2", gles2_names),
    ("libandroid", android_names),
    ("libEGL", egl_names),
    # Compatibility exports are append-only. Repeating an existing library appends symbols to
    # its assembly file without shifting any established host-call index.
    ("libandroid", android_compat_names),
    ("libEGL", egl_compat_names),
    ("libGLESv2", gles2_compat_names),
    ("libjnigraphics", jnigraphics_names),
    ("libandroid", looper_compat_names),
]


def main():
    out_asm = os.path.join(ROOT, "guest", "stubs", "gen")
    out_host = os.path.join(ROOT, "core", "src", "gen")
    os.makedirs(out_asm, exist_ok=True)
    os.makedirs(out_host, exist_ok=True)

    index = 0
    rows = []
    assemblies = {}
    for lib, source in LIBRARIES:
        names = source()
        if not names:
            sys.exit("no functions found for " + lib)
        lines = assemblies.setdefault(
            lib,
            [
                "@ Generated by tools/gen_stubs.py. Do not edit.",
                ".syntax unified",
                ".arm",
                ".text",
                "",
            ],
        )
        for name in names:
            if index >= RESERVED_HOST_CALL_FIRST:
                sys.exit("too many host calls: index 0x%x reaches the reserved range" % index)
            lines += [
                ".global %s" % name,
                ".type %s, %%function" % name,
                ".p2align 2",
                "%s:" % name,
                "    svc #0x%x" % (HOST_CALL_BASE | index),
                "    bx lr",
                ".size %s, . - %s" % (name, name),
                "",
            ]
            rows.append((index, lib + ".so", name))
            index += 1
        print("%s: %d functions" % (lib, len(names)))

    for lib, lines in assemblies.items():
        with open(os.path.join(out_asm, lib + ".S"), "w") as f:
            f.write("\n".join(lines))

    with open(os.path.join(out_host, "hostcalls.inc"), "w") as f:
        f.write("// Generated by tools/gen_stubs.py. Do not edit.\n")
        for i, lib, name in rows:
            f.write('{%d, "%s", "%s"},\n' % (i, lib, name))
    print("host calls: %d" % index)


if __name__ == "__main__":
    main()
